### ISSUE TITLE
ModuleNotFoundError: No module name 'colorama'

### ISSUE THREAD

**Issue by Jerry77474743737733n63** [clown83848474/Maths-Game#1]
### I got this error when i run the code 
```ModuleNotFoundError: No module name 'colorama'```

**Comment by clown83848474** [comment]
Hello , Make Sure To Install Colorama With Pip
``` pip install colorama ```
And It Will Work , Enjoy The Game 🔥
![Screenshot_2023-01-04-19-39-19.jpg](https://user-images.githubusercontent.com/114299126/210626206-689d9e1d-025e-4523-9f31-d98be079af46.jpg)

**Comment by Jerry77474743737733n63** [comment]
Thanks <3
